[package]
name = "c_test"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false

[package.metadata.release]
release = false

[dependencies]
imagequant-sys = { version = "4.0.3", path = ".." }

[build-dependencies]
cc = "1.0.95"
